services:
  server:
    build:
      context: ../server
    ports:
      - "5000:5000"
    volumes:
      - ../server/database.sqlite:/app/database.sqlite
    environment:
      - PORT=5000
      - NODE_ENV=production
      - JWT_SECRET=dev_secret_key_123
      # Add other environment variables here if needed

  client:
    build:
      context: ../client
    ports:
      - "3000:80"
    depends_on:
      - server
